name: Publish to crates.io

on:
  push:
    tags: ["v*.*.*"]

jobs:
  publish:
    uses: qntx/workflows/.github/workflows/publish-crates.yml@main
    with:
      packages: "actpub-activitystreams actpub-webfinger actpub-nodeinfo actpub-httpsig actpub-core actpub-federation actpub-axum actpub"
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
